# Generated by Django 5.1.8 on 2025-04-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.TextField(default="Untitled", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.TextField(default="Untitled", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
